table d_Regioes
	lineageTag: 3a3cba40-3a3c-4b78-a079-0000923be38d

	column UnidadeFederativa
		dataType: string
		lineageTag: a5002c0c-aac0-464a-9c59-1f6670aeaecb
		summarizeBy: none
		sourceColumn: UnidadeFederativa

		annotation SummarizationSetBy = Automatic

	column Sigla
		dataType: string
		lineageTag: dd7ebf21-8549-4ae6-a832-e6c734f75e6c
		summarizeBy: none
		sourceColumn: Sigla

		annotation SummarizationSetBy = Automatic

	column Região
		dataType: string
		lineageTag: f70630ab-f202-4afb-bd1b-da1eb3169f0f
		summarizeBy: none
		sourceColumn: Região

		annotation SummarizationSetBy = Automatic

	partition d_Regioes = m
		mode: import
		source =
				let
				    Fonte = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("bZJBboMwEEWvglinhyAkQY1KsOwsKkUsJsFKLIGNDEhVbxN10RW73sAX6wy0SXDYsJj/5/P87cMhjE5WhoswivGzM7aVYb7AaQlnAw0Jb6NQyOZfq6B2V5LYdKeCT6PHpXSiLOGiACfLyM+KJdghK1770ko1rVWtCTaykBZK1FcbckrdWvOS3Yzrpnb94BSgW4OWtcCP6O5ZiVHuSmBJNpeQggV9cV+0mz4xpoDRiTVNM+j7+YSbJygQpCPcVMxaFXYUJHgkRURp4rGyv0ZYNOkQx+D6I9XIlj4iiXrc4kNcOY6l1VAduxOBs6eGmYLO9SS9+hJXeA4ZbEFLZWmbbz1MciT4V3ThgUdOtO3mku6+sRguHiC50YX70cMD4dnkzNxgSdUg8IlAFw1BDC1YbJPC4odEgTcZMOhKAhfMAxfSnlVNsOKpkb05YbLSdDH7KQs9q3f6fNQ4A/dNzyXPfwE=", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [UnidadeFederativa = _t, Sigla = _t, Região = _t])
				in
				    Fonte

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

