table f_IndicadoresDW
	lineageTag: 4ca3d477-313c-461a-8a95-ad837bf994db

	column IdIndicador
		dataType: string
		lineageTag: fed31072-312f-40ef-93ea-5c18f3e4a84d
		summarizeBy: none
		sourceColumn: IdIndicador

		annotation SummarizationSetBy = Automatic

	column Ano
		dataType: int64
		formatString: 0
		lineageTag: 8eb3fdb6-7614-46fb-b986-6c83ab27ba01
		summarizeBy: sum
		sourceColumn: Ano

		annotation SummarizationSetBy = Automatic

	column Mes
		dataType: int64
		formatString: 0
		lineageTag: 524bf495-7547-4fbc-ab09-61909f596f00
		summarizeBy: sum
		sourceColumn: Mes

		annotation SummarizationSetBy = Automatic

	column RealizadoNumerador
		dataType: double
		lineageTag: d285aefc-705a-4bda-a731-d2812455289a
		summarizeBy: sum
		sourceColumn: RealizadoNumerador

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column RealizadoDenominador
		dataType: double
		lineageTag: f7d1c60c-2b26-477d-a827-f3e1b7c3bc98
		summarizeBy: sum
		sourceColumn: RealizadoDenominador

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column DiasUteis
		dataType: int64
		formatString: 0
		lineageTag: e45648a8-e8e2-4e53-97da-140f463c96fc
		summarizeBy: sum
		sourceColumn: DiasUteis

		annotation SummarizationSetBy = Automatic

	column MesAno
		dataType: dateTime
		formatString: Short Date
		lineageTag: 088da636-ddb0-49bf-9696-6c42ac61efcd
		summarizeBy: none
		sourceColumn: MesAno

		variation Variation
			isDefault
			relationship: e7491e15-7105-4dfc-90e1-b4593cf07156
			defaultHierarchy: LocalDateTable_29461e08-70e8-4ec5-a563-0b667c1e5492.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column ChvID
		dataType: string
		lineageTag: 229baa5b-a2b9-4597-8f9d-98596d2a005c
		summarizeBy: none
		sourceColumn: ChvID

		annotation SummarizationSetBy = Automatic

	partition f_IndicadoresDW = m
		mode: import
		queryGroup: AtlDiaria
		source =
				let
				    ID_3140_CustoFrete = Sql.Database("PR-S188\DW", "DW", [Query="DECLARE @DataInicial DATE = EOMONTH(DATEADD(MONTH, -4,GETDATE())); #(lf)DECLARE @MES INT;#(lf)DECLARE @ID INT;#(lf)#(lf)SELECT @ID = '3140' -- AT.CD.3140 - CUSTO DE FRETE AT - CIF#(lf)#(lf)SELECT @MES = MIN(Mes) #(lf)FROM DW.AT.GestaoMetas#(lf)WHERE IdIndicador = @ID#(lf)#(tab)AND MetaIndicador IS NOT NULL#(lf)#(tab)AND RealizadoNumerador IS NULL;#(lf)#(lf)WITH tbCustoFrete AS(#(lf)#(tab)SELECT gtb.[SerieNotaFiscal]#(lf)#(tab)#(tab),gtb.[NumeroNotaFiscal]#(lf)#(tab)#(tab),gtb.[DataSaida]#(lf)#(tab)#(tab),gtb.[QuantidadeFaturada] AS QtdeFat#(lf)#(tab)#(tab),CASE#(tab)#(lf)#(tab)#(tab)#(tab)WHEN ne.[sigla-emb] IS NULL THEN 0#(lf)#(tab)#(tab)#(tab)ELSE gtb.[VlFretePrevisto]#(lf)#(tab)#(tab)END AS FreteCorrigido#(lf)#(tab)FROM [DW].[logistica].[Fato_GTB] gtb#(lf)#(tab)#(tab)LEFT JOIN STAGE.tot.NotaEmbal ne#(lf)#(tab)#(tab)#(tab)ON DtEmisNota >  @DataInicial#(lf)#(tab)#(tab)#(tab)#(tab)AND [cod-estabel] = '15'#(lf)#(tab)#(tab)#(tab)#(tab)AND serie IN('5','21')#(lf)#(tab)#(tab)#(tab)#(tab)AND [nr-nota-fis] = gtb.NumeroNotaFiscal#(lf)#(tab)--#(lf)#(tab)WHERE gtb.Estabelecimento IN('15')#(lf)  #(tab)#(tab)AND gtb.SerieNotaFiscal IN(5, 21)#(lf)  #(tab)#(tab)AND gtb.DataEmissaoNotaFiscal > @DataInicial#(lf)  #(tab)#(tab)AND gtb.NumeroPedido NOT IN('')#(lf)#(tab)#(tab)AND gtb.NomeMatrizTransportador NOT IN('','Sem Info')#(lf)#(tab)#(tab)AND gtb.DataSaida BETWEEN DATEFROMPARTS(YEAR(GETDATE()), @MES, 1) #(lf)#(tab)#(tab)#(tab)AND EOMONTH(DATEFROMPARTS(YEAR(GETDATE()), @MES, 1))#(lf)#(tab)#(tab)AND gtb.NomeMatrizTransportador NOT LIKE 'BRITANIA%'#(lf)#(tab)#(tab)AND gtb.NomeMatrizTransportador NOT LIKE 'RETIRA%'#(lf))#(lf)SELECT @ID IdIndicador -- AT.CD.3140 - CUSTO DE FRETE AT - CIF#(lf)#(tab),YEAR(DATEFROMPARTS(YEAR(GETDATE()), @MES, 1)) Ano#(lf)#(tab),MONTH(DATEFROMPARTS(YEAR(GETDATE()), @MES, 1)) Mes#(lf)#(tab),SUM(FreteCorrigido) RealizadoNumerador#(lf)#(tab),SUM(QtdeFat) RealizadoDenominador#(lf)FROM tbCustoFrete"]),
				    ID_0628_ExpD2 = Sql.Database("PR-S188\DW", "DW", [Query="DECLARE @DataImplantacao DATE = EOMONTH(DATEADD(MONTH, - 4, GETDATE()));#(lf)DECLARE @MES INT;#(lf)DECLARE @ID INT;#(lf)#(lf)SELECT @ID = '628' -- AT.CD.0628 - PEÇAS EXPEDIDAS EM D+2#(lf)#(lf)SELECT @MES = MIN(Mes) #(lf)FROM DW.AT.GestaoMetas#(lf)WHERE IdIndicador = @ID #(lf)#(tab)AND RealizadoNumerador IS NULL#(lf)#(tab)AND MetaIndicador IS NOT NULL;#(lf)#(lf)WITH tbExpAT AS(#(lf)#(tab)SELECT CASE#(lf)#(tab)#(tab)#(tab)WHEN SomaDiaUtil.DiasExp > 2 THEN 'Atraso'#(lf)#(tab)#(tab)#(tab)ELSE 'Numerador'#(lf)#(tab)#(tab)END STATUS#(lf)#(tab)#(tab),pdb.QuantidadeAtendida QuantidadeAtendida#(lf)#(tab)FROM DW.logistica.Fato_PDB381 pdb WITH (NOLOCK)#(lf)#(tab)--Desconsidera Notas Canceladas#(lf)#(tab)LEFT JOIN auditoria.Fato_CustosFrete_Faturamento acf WITH (NOLOCK) ON pdb.NotaFiscal = acf.NumeroNotaFiscal#(lf)#(tab)#(tab)AND pdb.SerieNotaFiscal = acf.SerieNotaFiscal#(lf)#(tab)#(tab)AND acf.DataEmissaoNotaFiscal BETWEEN DATEFROMPARTS(YEAR(GETDATE()), @MES, 1) #(lf)#(tab)#(tab)#(tab)AND EOMONTH(DATEFROMPARTS(YEAR(GETDATE()), @MES, 1))#(lf)#(tab)-- Calcula Dias Úteis#(lf)#(tab)OUTER APPLY (#(lf)#(tab)#(tab)SELECT COALESCE(CASE #(lf)#(tab)#(tab)#(tab)#(tab)#(tab)WHEN SUM(CAST(DiaUtil AS INT)) - 1 < 0#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)THEN 0#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)ELSE SUM(CAST(DiaUtil AS INT)) - 1#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)END, 0) AS DiasExp#(lf)#(tab)#(tab)FROM DW.dbo.Dim_Data#(lf)#(tab)#(tab)WHERE Data BETWEEN CASE #(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)WHEN pdb.DataEmbarque IS NULL#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)THEN pdb.DtFaturamento#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)ELSE pdb.DataEmbarque#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)END#(lf)#(tab)#(tab)#(tab)#(tab)AND pdb.DataSaida#(lf)#(tab)#(tab)) SomaDiaUtil#(lf)#(tab)--#(lf)#(tab)WHERE pdb.DataImplantacao > @DataImplantacao#(lf)#(tab)#(tab)AND pdb.DataSaida BETWEEN DATEFROMPARTS(YEAR(GETDATE()), @MES, 1) #(lf)#(tab)#(tab)#(tab)AND EOMONTH(DATEFROMPARTS(YEAR(GETDATE()), @MES, 1))#(lf)#(tab)#(tab)AND pdb.SitPedido IN ('2','3','5')#(lf)#(tab)#(tab)AND pdb.SerieNotaFiscal IN (5,21)#(lf)#(tab)#(tab)AND acf.IdDataCancelamento IS NULL#(lf))#(lf)SELECT @ID IdIndicador -- AT.CD.0628 - PEÇAS EXPEDIDAS EM D+2#(lf)#(tab),YEAR(DATEFROMPARTS(YEAR(GETDATE()), @MES, 1)) Ano#(lf)#(tab),MONTH(DATEFROMPARTS(YEAR(GETDATE()), @MES, 1)) Mes#(lf)#(tab),SUM(CASE WHEN STATUS = 'Numerador' THEN QuantidadeAtendida ELSE 0 END) RealizadoNumerador#(lf)#(tab),SUM(QuantidadeAtendida)  RealizadoDenominador#(lf)FROM tbExpAT#(lf)"]),
				    ID_0568_IRP = Sql.Database("PR-S188\DW", "DW", [Query="DECLARE @DataImplantacao DATE = EOMONTH(DATEADD(MONTH, - 4, GETDATE()));#(lf)DECLARE @MES INT;#(lf)DECLARE @ID INT;#(lf)#(lf)SELECT @ID = '568' -- AT.CD.0568 - ÍNDICE DE RECLAMAÇÃO DOS POSTOS#(lf)#(lf)SELECT @MES = MIN(Mes) #(lf)FROM DW.AT.GestaoMetas#(lf)WHERE IdIndicador = @ID #(lf)#(tab)AND RealizadoNumerador IS NULL#(lf)#(tab)AND MetaIndicador IS NOT NULL;#(lf)#(lf)WITH tbIRP AS(#(lf)#(tab)SELECT DISTINCT CAST(pdb.DataSaida AS DATE) dtSaida#(lf)#(tab)#(tab),pdb.NotaFiscal#(lf)#(tab)#(tab),pdb.SerieNotaFiscal#(lf)#(tab)#(tab),pdb.EstabNotaFiscal#(lf)#(tab)#(tab),CASE #(lf)#(tab)#(tab)#(tab)WHEN RIGHT(pdb.NumeroOS, 3) = 'RPE'#(lf)#(tab)#(tab)#(tab)#(tab)THEN '-Errado'#(lf)#(tab)#(tab)#(tab)WHEN RIGHT(pdb.NumeroOS, 3) = 'RPQ'#(lf)#(tab)#(tab)#(tab)#(tab)THEN '-Qudebrado'#(lf)#(tab)#(tab)#(tab)WHEN RIGHT(pdb.NumeroOS, 3) = 'RPF'#(lf)#(tab)#(tab)#(tab)#(tab)THEN '-Faltante'#(lf)#(tab)#(tab)#(tab)ELSE NULL#(lf)#(tab)#(tab)END IRP#(lf)#(tab)FROM DW.logistica.Fato_PDB381 pdb WITH (NOLOCK)#(lf)#(tab)--Desconsidera Notas Canceladas#(lf)#(tab)LEFT JOIN auditoria.Fato_CustosFrete_Faturamento acf WITH (NOLOCK) ON pdb.NotaFiscal = acf.NumeroNotaFiscal#(lf)#(tab)#(tab)AND pdb.SerieNotaFiscal = acf.SerieNotaFiscal#(lf)#(tab)#(tab)AND acf.DataEmissaoNotaFiscal BETWEEN DATEFROMPARTS(YEAR(GETDATE()), @MES, 1) #(lf)#(tab)#(tab)#(tab)AND EOMONTH(DATEFROMPARTS(YEAR(GETDATE()), @MES, 1))#(lf)#(tab)WHERE acf.IdDataCancelamento IS NULL#(lf)#(tab)#(tab)AND  pdb.DataImplantacao > @DataImplantacao#(lf)#(tab)#(tab)AND pdb.DataSaida BETWEEN DATEFROMPARTS(YEAR(GETDATE()), @MES, 1) #(lf)#(tab)#(tab)#(tab)AND EOMONTH(DATEFROMPARTS(YEAR(GETDATE()), @MES, 1))#(lf)#(tab)#(tab)AND pdb.SitPedido IN ('2','3','5')#(lf)#(tab)#(tab)AND pdb.SerieNotaFiscal IN (5,21)#(lf))#(lf)SELECT @ID IdIndicador -- AT.CD.0568 - ÍNDICE DE RECLAMAÇÃO DOS POSTOS#(lf)#(tab),YEAR(DATEFROMPARTS(YEAR(GETDATE()), @MES, 1)) Ano#(lf)#(tab),MONTH(DATEFROMPARTS(YEAR(GETDATE()), @MES, 1)) Mes#(lf)#(tab),SUM(CASE WHEN IRP IS NOT NULL THEN 1 ELSE 0 END) RealizadoNumerador #(lf)#(tab),COUNT(NotaFiscal) RealizadoDenominador#(lf)FROM tbIRP"]),
				    DI_0058_EntregaPrazo = Sql.Database("PR-S188\DW", "DW", [Query="DECLARE @MES INT;#(lf)DECLARE @ID INT;#(lf)#(lf)SELECT @ID = '58' --  AT.CD.0058 - % ENTREGAS NO PRAZO AT#(lf)#(lf)SELECT @MES = MIN(Mes) #(lf)FROM DW.AT.GestaoMetas#(lf)WHERE IdIndicador = @ID#(lf)#(tab)AND RealizadoNumerador IS NULL#(lf)#(tab)AND MetaIndicador IS NOT NULL;#(lf)#(lf)WITH tbEntrga AS(#(lf)#(tab)SELECT DISTINCT aud.SerieNotaFiscal#(lf)#(tab)#(tab),aud.NumeroNotaFiscal#(lf)#(tab)#(tab),CAST(dtsaida.Data AS DATE) DataSaida#(lf)#(tab)#(tab),CAST(dtentrega.Data AS DATE) DataEntrega#(lf)#(tab)#(tab)-- Notas com data de programação de entrega serão consideradas No Prazo #(lf)#(tab)#(tab), CASE#(lf)#(tab)#(tab)#(tab)WHEN IdDataProgEntrega IS NOT NULL THEN 'NO PRAZO'#(lf)#(tab)#(tab)#(tab)WHEN SomaDiaUtil.DiasExp <= aud.TransTime THEN 'NO PRAZO'#(lf)#(tab)#(tab)#(tab)ELSE 'ATRASO'#(lf)#(tab)#(tab)END STATUS#(lf)#(tab)FROM auditoria.Fato_CustosFrete_Faturamento aud#(lf)#(tab)#(tab)LEFT JOIN dbo.Dim_Data dtsaida #(lf)#(tab)#(tab)#(tab)ON aud.IdDataSaida = dtsaida.id#(lf)#(tab)#(tab)LEFT JOIN dbo.Dim_Data dtentrega #(lf)#(tab)#(tab)#(tab)ON aud.IdDataEntrega = dtentrega.id#(lf)#(tab)OUTER APPLY (#(lf)#(tab)#(tab)SELECT COALESCE(CASE #(lf)#(tab)#(tab)#(tab)#(tab)#(tab)WHEN SUM(CAST(DiaUtil AS INT)) - 1 < 0#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)THEN 0#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)ELSE SUM(CAST(DiaUtil AS INT)) - 1#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)END, 0) AS DiasExp#(lf)#(tab)#(tab)FROM DW.dbo.Dim_Data#(lf)#(tab)#(tab)WHERE Data BETWEEN dtsaida.Data#(tab)AND dtentrega.Data#(lf)#(tab)#(tab)) SomaDiaUtil#(lf)#(tab)WHERE aud.SerieNotaFiscal IN (5#(tab),21)#(lf)#(tab)#(tab)AND aud.IdEstab = 8#(lf)#(tab)#(tab)AND dtentrega.Data BETWEEN DATEFROMPARTS(YEAR(GETDATE()), @MES, 1) #(lf)#(tab)#(tab)#(tab)AND EOMONTH(DATEFROMPARTS(YEAR(GETDATE()), @MES, 1))#(lf)#(tab)#(tab)AND aud.IdDataCancelamento IS NULL#(lf))#(lf)SELECT @ID IdIndicador --  AT.CD.0058 - % ENTREGAS NO PRAZO AT#(lf)#(tab),YEAR(DATEFROMPARTS(YEAR(GETDATE()), @MES, 1)) Ano#(lf)#(tab),MONTH(DATEFROMPARTS(YEAR(GETDATE()), @MES, 1)) Mes#(lf)#(tab),SUM(CASE WHEN STATUS = 'NO PRAZO' THEN 1 ELSE 0 END) RealizadoNumerador#(lf)#(tab),COUNT(STATUS) RealizadoDenominador#(lf)FROM tbEntrga"]),
				    ID_2509_Produtividade = Sql.Database("PR-S188\DW", "DW", [Query="--EXPEDIÇÃO AT#(lf)DECLARE @DataImplantacao DATE = EOMONTH(DATEADD(MONTH, - 4, GETDATE()));#(lf)DECLARE @MES INT;#(lf)DECLARE @ID INT;#(lf)#(lf)SELECT @ID = '2509' -- AT.CD.2509 - PRODUTIVIDADE AT#(lf)#(lf)SELECT @MES = MIN(Mes) #(lf)FROM DW.AT.GestaoMetas#(lf)WHERE IdIndicador = @ID #(lf)#(tab)AND RealizadoNumerador IS NULL#(lf)#(tab)AND MetaIndicador IS NOT NULL;#(lf)#(lf)WITH tbExpedicao AS(#(lf)#(tab)SELECT SUM(pdb.QuantidadeAtendida) Expedicao#(lf)#(tab)FROM DW.logistica.Fato_PDB381 pdb WITH (NOLOCK)#(lf)#(tab)--Desconsidera Notas Canceladas#(lf)#(tab)LEFT JOIN auditoria.Fato_CustosFrete_Faturamento acf WITH (NOLOCK) ON pdb.NotaFiscal = acf.NumeroNotaFiscal#(lf)#(tab)#(tab)AND pdb.SerieNotaFiscal = acf.SerieNotaFiscal#(lf)#(tab)#(tab)AND acf.DataEmissaoNotaFiscal BETWEEN DATEFROMPARTS(YEAR(GETDATE()), @MES, 1) #(lf)#(tab)#(tab)#(tab)AND EOMONTH(DATEFROMPARTS(YEAR(GETDATE()), @MES, 1))#(lf)#(tab)WHERE pdb.DataImplantacao > @DataImplantacao#(lf)#(tab)#(tab)AND pdb.DataSaida BETWEEN DATEFROMPARTS(YEAR(GETDATE()), @MES, 1) #(lf)#(tab)#(tab)#(tab)AND EOMONTH(DATEFROMPARTS(YEAR(GETDATE()), @MES, 1)) #(lf)#(tab)#(tab)AND pdb.SitPedido IN ('2','3','5')#(lf)#(tab)#(tab)AND pdb.SerieNotaFiscal IN (5,21)#(lf)#(tab)#(tab)AND acf.IdDataCancelamento IS NULL#(lf)),#(lf)tbRecebimento AS(#(lf)#(tab)--Calculo Recebimento#(lf)#(tab)SELECT SUM(QtdeItemMov) Recebimento#(lf)#(tab)FROM (#(lf)#(tab)#(tab)SELECT DISTINCT NumeroDocumento#(lf)#(tab)#(tab)#(tab)#(tab),QtdeItemMov#(lf)#(tab)#(tab)#(tab)FROM logistica.Fato_Mov_Estoque_PA_AT feat#(lf)#(tab)#(tab)#(tab)WHERE  LOCAL = 'AAT'#(lf)#(tab)#(tab)#(tab)#(tab)AND feat.Movimento = 'Entrada'#(lf)#(tab)#(tab)#(tab)#(tab)AND feat.Origem = 'Transferência Origem'#(lf)#(tab)#(tab)#(tab)#(tab)AND feat.DtFimTarefa BETWEEN DATEFROMPARTS(YEAR(GETDATE()), @MES, 1) #(lf)#(tab)#(tab)#(tab)#(tab)AND EOMONTH(DATEFROMPARTS(YEAR(GETDATE()), @MES, 1))#(lf)#(tab)) AS MovEst#(lf)),#(lf)tbDesmonte AS(#(lf)#(tab)--Calculo Desmonte#(lf)#(tab)SELECT SUM(Quantidade) Desmonte#(lf)#(tab)FROM logistica.Fato_WM0620#(lf)#(tab)WHERE Documento LIKE '%DESC%'#(lf)#(tab)#(tab)AND Quantidade IS NOT NULL#(lf)#(tab)#(tab)AND DtFimTarefa BETWEEN DATEFROMPARTS(YEAR(GETDATE()), @MES, 1) #(lf)#(tab)#(tab)#(tab)#(tab)AND EOMONTH(DATEFROMPARTS(YEAR(GETDATE()), @MES, 1))#(lf)#(tab)#(tab)AND Local = 'AAT'#(lf)),#(lf)tbRessup AS(#(lf)#(tab)--Calculo Ressuprimento#(lf)#(tab)SELECT SUM(QtdeItemMov) Ressuprimento#(lf)#(tab)FROM  (#(lf)#(tab)#(tab)SELECT DISTINCT NumeroDocumento#(tab)#(lf)#(tab)#(tab)#(tab),QtdeItemMov#(lf)#(tab)#(tab)FROM logistica.Fato_Mov_Estoque_PA_AT feat#(lf)#(tab)#(tab)WHERE  LOCAL = 'AAT'#(lf)#(tab)#(tab)#(tab)AND feat.Movimento = 'Entrada'#(lf)#(tab)#(tab)#(tab)AND feat.Origem = 'Transferência Destino'#(lf)#(tab)#(tab)#(tab)AND feat.DtFimTarefa BETWEEN DATEFROMPARTS(YEAR(GETDATE()), @MES, 1) #(lf)#(tab)#(tab)#(tab)#(tab)#(tab)AND EOMONTH(DATEFROMPARTS(YEAR(GETDATE()), @MES, 1))#(lf)#(tab)) AS tbRessup#(lf)),#(lf)tbFuncionarios AS(#(lf)-- CALCULO FUNCIONARIOS#(lf)-- Não considerar horário comercial#(lf)-- Considerar op deposito, op empilhadeira, conferente e almoxarife#(lf)-- Data de Admissão 10 dias anterior a data atual#(lf)SELECT COUNT(DISTINCT f.cdn_funcionario) qtdeFuncionarios#(lf)FROM STAGE.tot.Funcionario f#(lf)#(tab)LEFT JOIN [STAGE].tot.SitAfastFunc sa#(lf)#(tab)#(tab)ON sa.cdn_estab = f.cdn_estab#(lf)#(tab)#(tab)#(tab)AND sa.cdn_empresa = f.cdn_empresa#(lf)#(tab)#(tab)#(tab)AND sa.cdn_funcionario = f.cdn_funcionario#(lf)#(tab)#(tab)#(tab)-- MOTIVO AFASTAMENTO - SUPERIOR A 15 DIAS OU MATERNIDADE#(lf)#(tab)#(tab)#(tab)AND sa.cdn_sit_afast_func IN('17','21','22','50')#(lf)#(tab)JOIN STAGE.tot.RHCargo cg#(lf)#(tab)#(tab)ON f.cdn_cargo_basic = cg.cdn_cargo_basic#(lf)#(tab)#(tab)#(tab)AND (cg.des_cargo LIKE 'OPERADOR DE DEP%'#(lf)#(tab)#(tab)#(tab)#(tab)OR cg.des_cargo LIKE 'ALMOXAR%'#(lf)#(tab)#(tab)#(tab)#(tab)OR cg.des_cargo LIKE 'OPERADOR DE EMP%'#(lf)#(tab)#(tab)#(tab)#(tab)OR cg.des_cargo LIKE 'CONFERENTE%'#(lf)#(tab)#(tab)#(tab))#(lf)#(tab)#(tab)#(tab)AND NOT cg.des_cargo LIKE '%MATERIAIS%'#(lf)#(tab)JOIN STAGE.tot.RHTurnoTrabalho tt#(lf)#(tab)#(tab)ON f.cdn_turno_trab = tt.cdn_turno_trab#(lf)#(tab)#(tab)#(tab)AND (tt.des_turno_trab LIKE 'TA%'#(lf)#(tab)#(tab)#(tab)#(tab)OR tt.des_turno_trab LIKE 'TB%'#(lf)#(tab)#(tab)#(tab)#(tab)OR tt.des_turno_trab LIKE 'TC%')#(lf)WHERE f.cod_rh_ccusto = '23210'#(lf)#(tab)AND f.dat_desligto_func IS NULL#(lf)#(tab)AND sa.dat_term_proces_sit_afast <= CAST(GETDATE() AS DATE)#(lf)#(tab)AND f.dat_admis_func < DATEADD(DAY, -10,CAST(GETDATE() AS DATE))#(lf)),#(lf)-- Calcula Dias Úteis#(lf)tbDiasUteis AS(#(lf)#(tab)SELECT COALESCE(CASE #(lf)#(tab)#(tab)#(tab)#(tab)WHEN SUM(CAST(DiaUtil AS INT)) - 1 < 0#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)THEN 0#(lf)#(tab)#(tab)#(tab)#(tab)ELSE SUM(CAST(DiaUtil AS INT)) - 1#(lf)#(tab)#(tab)#(tab)#(tab)END, 0) AS DiasUteis#(lf)#(tab)FROM DW.dbo.Dim_Data#(lf)#(tab)WHERE Data BETWEEN DATEFROMPARTS(YEAR(GETDATE()), @MES, 1) #(lf)#(tab)#(tab)#(tab)#(tab)#(tab)AND CASE WHEN GETDATE() > EOMONTH(DATEFROMPARTS(YEAR(GETDATE()), @MES, 1)) THEN#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab) EOMONTH(DATEFROMPARTS(YEAR(GETDATE()), @MES, 1)) ELSE CAST(GETDATE() AS DATE)#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)END#(lf))#(lf)SELECT  @ID IdIndicador -- AT.CD.2509 - PRODUTIVIDADE AT#(lf)#(tab),YEAR(DATEFROMPARTS(YEAR(GETDATE()), @MES, 1)) Ano#(lf)#(tab),MONTH(DATEFROMPARTS(YEAR(GETDATE()), @MES, 1)) Mes#(lf)#(tab),ISNULL(tbDesmonte.Desmonte, 0) +#(lf)#(tab)#(tab)ISNULL(tbExpedicao.Expedicao, 0) +#(lf)#(tab)#(tab)ISNULL(tbRecebimento.Recebimento, 0) +#(lf)#(tab)#(tab)ISNULL(tbRessup.Ressuprimento, 0) AS RealizadoNumerador#(lf)#(tab),tbFuncionarios.qtdeFuncionarios RealizadoDenominador#(lf)#(tab),tbDiasUteis.DiasUteis#(lf)FROM tbDesmonte#(lf)#(tab),tbExpedicao#(lf)#(tab),tbRecebimento#(lf)#(tab),tbRessup#(lf)#(tab),tbFuncionarios#(lf)#(tab),tbDiasUteis"]),
				    ID_3139_Ageing130 = Sql.Database("PR-S188\DW", "DW", [Query="DECLARE @MES INT;#(lf)DECLARE @ID INT;#(lf)#(lf)SELECT @ID = '3139' -- AT.AG.3139 - AGING DEPÓSITOS TRANSITÓRIOS CDAT ESTABELECIMENTO 130#(lf)#(lf)SELECT @MES = MIN(Mes) #(lf)FROM DW.AT.GestaoMetas#(lf)WHERE IdIndicador = @ID#(lf)#(tab)AND MetaIndicador IS NOT NULL#(lf)#(tab)AND RealizadoNumerador IS NULL;#(lf)#(lf)WITH tbAging AS(#(lf)#(tab)SELECT est.CodEstab#(lf)#(tab)#(tab),dep.CodigoDeposito#(lf)#(tab)#(tab),SUM(fem.ValorDentroMeta) vlDentroMeta#(lf)#(tab)#(tab),SUM(fem.ValorForaMeta) vlForaMeta#(lf)#(tab)#(tab),SUM(fem.ValorDentroMeta) + SUM(fem.ValorForaMeta) vlTotal#(lf)#(tab)FROM dbo.Fato_EstoqueMeta fem#(lf)#(tab)INNER JOIN dbo.Dim_Deposito dep#(lf)#(tab)#(tab)ON fem.IdDeposito = dep.IdDeposito#(lf)#(tab)#(tab)#(tab)AND dep.CodigoDeposito IN('BEC','DRE','RCB','REC')#(lf)#(tab)LEFT JOIN dbo.Dim_Estabelecimento est#(lf)#(tab)#(tab)ON fem.IdEstabelec = est.Id#(lf)#(tab)WHERE IdEstabelec = '59' --130#(lf)#(tab)#(tab)AND fem.IdData =  (SELECT MAX(IdData) FROM dbo.Fato_EstoqueMeta) #(lf)#(tab)GROUP BY est.CodEstab#(lf)#(tab)#(tab),dep.CodigoDeposito#(lf))#(lf)SELECT @ID IdIndicador -- AT.AG.3139 - AGING DEPÓSITOS TRANSITÓRIOS CDAT ESTABELECIMENTO 130#(lf)#(tab),YEAR(DATEFROMPARTS(YEAR(GETDATE()), @MES, 1)) Ano#(lf)#(tab),MONTH(DATEFROMPARTS(YEAR(GETDATE()), @MES, 1)) Mes#(lf)#(tab),SUM(vlDentroMeta) RealizadoNumerador#(lf)#(tab),SUM(vlTotal) RealizadoDenominador#(lf)FROM tbAging"]),
				    ID_3399_Ageng31 = Sql.Database("PR-S188\DW", "DW", [Query="DECLARE @MES INT;#(lf)DECLARE @ID INT;#(lf)#(lf)SELECT @ID = '3399' -- AT.CD.3399 - AGING DEPÓSITOS TRANSITÓRIOS CDAT ESTABELECIMENTO 31#(lf)#(lf)SELECT @MES = MIN(Mes) #(lf)FROM DW.AT.GestaoMetas#(lf)WHERE IdIndicador = @ID #(lf)#(tab)AND RealizadoNumerador IS NULL#(lf)#(tab)AND MetaIndicador IS NOT NULL;#(lf)#(lf)WITH tbAging AS(#(lf)#(tab)SELECT est.CodEstab#(lf)#(tab)#(tab),dep.CodigoDeposito#(lf)#(tab)#(tab),SUM(fem.ValorDentroMeta) vlDentroMeta#(lf)#(tab)#(tab),SUM(fem.ValorForaMeta) vlForaMeta#(lf)#(tab)#(tab),SUM(fem.ValorDentroMeta) + SUM(fem.ValorForaMeta) vlTotal#(lf)#(tab)FROM dbo.Fato_EstoqueMeta fem#(lf)#(tab)INNER JOIN dbo.Dim_Deposito dep#(lf)#(tab)#(tab)ON fem.IdDeposito = dep.IdDeposito#(lf)#(tab)#(tab)#(tab)AND dep.CodigoDeposito IN('BEC','DRE')#(lf)#(tab)LEFT JOIN dbo.Dim_Estabelecimento est#(lf)#(tab)#(tab)ON fem.IdEstabelec = est.Id#(lf)#(tab)WHERE IdEstabelec = '26' --31#(lf)#(tab)#(tab)AND fem.IdData =  (SELECT MAX(IdData) FROM dbo.Fato_EstoqueMeta) #(lf)#(tab)GROUP BY est.CodEstab#(lf)#(tab)#(tab),dep.CodigoDeposito#(lf))#(lf)SELECT @ID IdIndicador -- AT.CD.3399 - AGING DEPÓSITOS TRANSITÓRIOS CDAT ESTABELECIMENTO 31#(lf)#(tab),YEAR(DATEFROMPARTS(YEAR(GETDATE()), @MES, 1)) Ano#(lf)#(tab),MONTH(DATEFROMPARTS(YEAR(GETDATE()), @MES, 1)) Mes#(lf)#(tab),SUM(vlDentroMeta) RealizadoNumerador#(lf)#(tab),SUM(vlTotal) RealizadoDenominador#(lf)FROM tbAging"]),
				    ID_3400_Aging22 = Sql.Database("PR-S188\DW", "DW", [Query="DECLARE @MES INT;#(lf)DECLARE @ID INT;#(lf)#(lf)SELECT @ID = '3400' --AT.CD.3400 - AGING DEPÓSITOS TRANSITÓRIOS CDAT ESTABELECIMENTO 22#(lf)#(lf)SELECT @MES = MIN(Mes) #(lf)FROM DW.AT.GestaoMetas#(lf)WHERE IdIndicador = @ID #(lf)#(tab)AND RealizadoNumerador IS NULL#(lf)#(tab)AND MetaIndicador IS NOT NULL;#(lf)#(lf)WITH tbAging AS(#(lf)#(tab)SELECT est.CodEstab#(lf)#(tab)#(tab),dep.CodigoDeposito#(lf)#(tab)#(tab),SUM(fem.ValorDentroMeta) vlDentroMeta#(lf)#(tab)#(tab),SUM(fem.ValorForaMeta) vlForaMeta#(lf)#(tab)#(tab),SUM(fem.ValorDentroMeta) + SUM(fem.ValorForaMeta) vlTotal#(lf)#(tab)FROM dbo.Fato_EstoqueMeta fem#(lf)#(tab)INNER JOIN dbo.Dim_Deposito dep#(lf)#(tab)#(tab)ON fem.IdDeposito = dep.IdDeposito#(lf)#(tab)#(tab)#(tab)AND dep.CodigoDeposito IN('BEC','DRE')#(lf)#(tab)LEFT JOIN dbo.Dim_Estabelecimento est#(lf)#(tab)#(tab)ON fem.IdEstabelec = est.Id#(lf)#(tab)WHERE IdEstabelec = '18' -- 22#(lf)#(tab)#(tab)AND fem.IdData =  (SELECT MAX(IdData) FROM dbo.Fato_EstoqueMeta) #(lf)#(tab)GROUP BY est.CodEstab#(lf)#(tab)#(tab),dep.CodigoDeposito#(lf))#(lf)SELECT @ID IdIndicador -- AT.CD.3400 - AGING DEPÓSITOS TRANSITÓRIOS CDAT ESTABELECIMENTO 22#(lf)#(tab),YEAR(DATEFROMPARTS(YEAR(GETDATE()), @MES, 1)) Ano#(lf)#(tab),MONTH(DATEFROMPARTS(YEAR(GETDATE()), @MES, 1)) Mes#(lf)#(tab),SUM(vlDentroMeta) RealizadoNumerador#(lf)#(tab),SUM(vlTotal) RealizadoDenominador#(lf)FROM tbAging"]),
				    ID_2299_Aging15 = Sql.Database("PR-S188\DW", "DW", [Query="DECLARE @MES INT;#(lf)DECLARE @ID INT;#(lf)#(lf)SELECT @ID = '2299' -- AT.CD.2299 - AGING DEPÓSITOS TRANSITÓRIOS CDAT ESTABELECIMENTO 15#(lf)#(lf)SELECT @MES = MIN(Mes) #(lf)FROM DW.AT.GestaoMetas#(lf)WHERE IdIndicador = @ID #(lf)#(tab)AND RealizadoNumerador IS NULL#(lf)#(tab)AND MetaIndicador IS NOT NULL;#(lf)#(lf)WITH tbAging AS(#(lf)#(tab)SELECT est.CodEstab#(lf)#(tab)#(tab),dep.CodigoDeposito#(lf)#(tab)#(tab),SUM(fem.ValorDentroMeta) vlDentroMeta#(lf)#(tab)#(tab),SUM(fem.ValorForaMeta) vlForaMeta#(lf)#(tab)#(tab),SUM(fem.ValorDentroMeta) + SUM(fem.ValorForaMeta) vlTotal#(lf)#(tab)FROM dbo.Fato_EstoqueMeta fem#(lf)#(tab)INNER JOIN dbo.Dim_Deposito dep#(lf)#(tab)#(tab)ON fem.IdDeposito = dep.IdDeposito#(lf)#(tab)#(tab)#(tab)AND dep.CodigoDeposito IN('BEC','DCV','DES','DEV','DNV','DRE','ENG','NAT','RCB','REC','ATE')#(lf)#(tab)LEFT JOIN dbo.Dim_Estabelecimento est#(lf)#(tab)#(tab)ON fem.IdEstabelec = est.Id#(lf)#(tab)WHERE IdEstabelec = '8' -- 15#(lf)#(tab)#(tab)AND fem.IdData =  (SELECT MAX(IdData) FROM dbo.Fato_EstoqueMeta) #(lf)#(tab)GROUP BY est.CodEstab#(lf)#(tab)#(tab),dep.CodigoDeposito#(lf))#(lf)SELECT @ID IdIndicador -- AT.CD.2299 - AGING DEPÓSITOS TRANSITÓRIOS CDAT ESTABELECIMENTO 15#(lf)#(tab),YEAR(DATEFROMPARTS(YEAR(GETDATE()), @MES, 1)) Ano#(lf)#(tab),MONTH(DATEFROMPARTS(YEAR(GETDATE()), @MES, 1)) Mes#(lf)#(tab),SUM(vlDentroMeta) RealizadoNumerador#(lf)#(tab),SUM(vlTotal) RealizadoDenominador#(lf)FROM tbAging"]),
				    ID_2985_2986_DiasOs = Sql.Database("PR-S188\DW", "DW", [Query="DECLARE @DataImplantacao DATE = EOMONTH(DATEADD(MONTH, - 4, GETDATE()));#(lf)DECLARE @MES INT;#(lf)#(lf)SELECT @MES = MIN(Mes)#(lf)FROM DW.AT.GestaoMetas#(lf)WHERE IdIndicador = '2985' --  AT.CD.2985 - ATENDIMENTO DE PEÇAS COM OS EM ATÉ DOIS DIAS ÚTEIS#(lf)#(tab)AND MetaIndicador IS NOT NULL#(lf)#(tab)AND RealizadoNumerador IS NULL;#(lf)#(lf)-- Valida se tabela Temp existe e Deleta#(lf)IF OBJECT_ID('tempdb..#Filtered_PDB') IS NOT NULL#(lf)#(tab)DROP TABLE #Filtered_PDB;#(lf)#(lf)#(lf)SELECT p.NumeroPedido#(lf)#(tab),p.DataImplantacao#(lf)#(tab),p.CodEmitente#(lf)#(tab),p.QuantidadeAtendida#(lf)#(tab),p.DataSaida#(lf)#(tab),p.NotaFiscal#(lf)#(tab),p.SerieNotaFiscal#(lf)#(tab),p.EstabNotaFiscal#(lf)#(tab),p.SitCreditoPed#(lf)#(tab),p.CreditoPosto#(lf)#(tab),p.PedidoCompleto#(lf)#(tab),p.SitPedido#(lf)#(tab),p.CreditoCliente#(lf)#(tab),p.SitCredenciamento#(lf)INTO #Filtered_PDB#(lf)FROM DW.logistica.Fato_PDB381 p WITH (NOLOCK)#(lf)--Desconsidera Notas Canceladas#(lf)LEFT JOIN auditoria.Fato_CustosFrete_Faturamento acf WITH (NOLOCK) #(lf)#(tab)ON p.NotaFiscal = acf.NumeroNotaFiscal#(lf)#(tab)#(tab)AND p.SerieNotaFiscal = acf.SerieNotaFiscal#(lf)#(tab)#(tab)AND acf.DataEmissaoNotaFiscal >= @DataImplantacao#(lf)WHERE p.DataImplantacao > @DataImplantacao#(lf)#(tab)AND p.DataSaida BETWEEN DATEFROMPARTS(YEAR(GETDATE()), @MES, 1) #(lf)#(tab)#(tab)AND EOMONTH(DATEFROMPARTS(YEAR(GETDATE()), @MES, 1))#(lf)#(tab)AND p.SitPedido IN ('2','3','5')#(lf)#(tab)AND p.SerieNotaFiscal IN (5,21)#(lf)#(tab)AND p.NumeroOS <> ''#(lf)#(tab)AND acf.IdDataCancelamento IS NULL;#(lf)#(lf)-- Consulta Log de Erro FTB400#(lf)WITH ConsLog AS (#(lf)#(tab)SELECT DISTINCT lg.POSTO#(lf)#(tab)#(tab),FORMAT(lg.DATA_ARQUIVO, 'yyyyMM') AS ANO_MES#(lf)#(tab)#(tab),lg.PEDIDO + CAST(lg.POSTO AS VARCHAR) AS ChvPedCliente#(lf)#(tab)#(tab),'Log Erro' AS LOG_ERRO#(lf)#(tab)FROM STAGE.excel.LogErroFTB400 lg WITH (NOLOCK)#(lf)#(tab)WHERE DATA_ARQUIVO BETWEEN DATEFROMPARTS(YEAR(GETDATE()), @MES, 1) #(lf)#(tab)#(tab)AND EOMONTH(DATEFROMPARTS(YEAR(GETDATE()), @MES, 1))#(lf)#(lf)#(tab)#(tab)AND NOT EXISTS (#(lf)#(tab)#(tab)#(tab)SELECT 1#(lf)#(tab)#(tab)#(tab)FROM (#(lf)#(tab)#(tab)#(tab)#(tab)VALUES ('Estado diferente')#(lf)#(tab)#(tab)#(tab)#(tab)#(tab),('Natureza em garantia e emite duplicata')#(lf)#(tab)#(tab)#(tab)#(tab)#(tab),('Emitente fora da faixa')#(lf)#(tab)#(tab)#(tab)#(tab)#(tab),('atendido total ou cance')#(lf)#(tab)#(tab)#(tab)#(tab)#(tab),('embarcado ou faturado')#(lf)#(tab)#(tab)#(tab)#(tab)#(tab),('')#(lf)#(tab)#(tab)#(tab)#(tab)) AS l(Descricao)#(lf)#(tab)#(tab)#(tab)WHERE CHARINDEX(l.Descricao, lg.LOG_DE_ERRO) > 0#(lf)#(tab)#(tab)#(tab))#(lf)),#(lf)tbPdbCalc AS (#(lf)#(tab)SELECT #(lf)#(tab)CAST(pdb.QuantidadeAtendida AS INT) AS QuantidadeAtendida#(lf)#(tab),pdb.NotaFiscal#(lf)#(tab),pdb.SerieNotaFiscal#(lf)#(tab),CASE #(lf)#(tab)#(tab)WHEN UPPER(pdb.SitCredenciamento) = 'N'#(lf)#(tab)#(tab)#(tab)THEN 'LogErro'#(lf)#(tab)#(tab)WHEN pdb.SitCreditoPed = 'Não Aprovado' #(lf)#(tab)#(tab)#(tab)THEN 'LogErro'#(lf)#(tab)#(tab)ELSE cl.LOG_ERRO#(lf)#(tab)END AS Log_Erro#(lf)#(tab),SomaDiaUtil.DiasExp DiaUtil_SemLog#(lf)#(tab), DATEDIFF(DAY, pdb.DataImplantacao, pdb.DataSaida) DiasCorridos#(lf)FROM #Filtered_PDB pdb#(lf)LEFT JOIN dbo.Dim_SituacaoPedido sp WITH (NOLOCK) ON pdb.SitPedido = sp.CodSitPed#(lf)LEFT JOIN ConsLog cl WITH (NOLOCK) ON FORMAT(pdb.DataSaida, 'yyyyMM') = cl.ANO_MES#(lf)#(tab)AND pdb.NumeroPedido + CAST(pdb.CodEmitente AS VARCHAR) = cl.ChvPedCliente#(lf)#(lf)-- Calcula Dias Úteis#(lf)OUTER APPLY (#(lf)#(tab)SELECT COALESCE(CASE #(lf)#(tab)#(tab)#(tab)#(tab)WHEN SUM(CAST(DiaUtil AS INT)) - 1 < 0#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)THEN 0#(lf)#(tab)#(tab)#(tab)#(tab)ELSE SUM(CAST(DiaUtil AS INT)) - 1#(lf)#(tab)#(tab)#(tab)#(tab)END, 0) AS DiasExp#(lf)#(tab)FROM DW.dbo.Dim_Data#(lf)#(tab)WHERE Data BETWEEN pdb.DataImplantacao AND pdb.DataSaida#(lf)#(tab)) SomaDiaUtil#(lf))#(lf)#(lf)--SELECT *#(lf)--FROM tbPdbCalc#(lf)#(lf)SELECT '2985' IdIndicador -- AT.CD.2985 - ATENDIMENTO DE PEÇAS COM OS EM ATÉ DOIS DIAS ÚTEIS#(lf)#(tab),YEAR(DATEFROMPARTS(YEAR(GETDATE()), @MES, 1)) Ano#(lf)#(tab),MONTH(DATEFROMPARTS(YEAR(GETDATE()), @MES, 1)) Mes#(lf)#(tab),SUM(CASE WHEN DiaUtil_SemLog < 3 THEN QuantidadeAtendida ELSE 0 END) RealizadoNumerador #(lf)#(tab),SUM(CASE WHEN Log_Erro IS NULL AND DiaUtil_SemLog > 2 THEN QuantidadeAtendida ELSE 0 END)#(lf)#(tab)#(tab)+ SUM(CASE WHEN DiaUtil_SemLog < 3 THEN QuantidadeAtendida ELSE 0 END) RealizadoDenominador#(lf)FROM tbPdbCalc#(lf)--#(lf)UNION ALL#(lf)--#(lf)SELECT '2986' IdIndicador -- AT.CD.2986 - ATENDIMENTO DE PEÇAS COM OS EM ATÉ DOIS DIAS CORRIDOS#(lf)#(tab),YEAR(DATEFROMPARTS(YEAR(GETDATE()), @MES, 1)) Ano#(lf)#(tab),MONTH(DATEFROMPARTS(YEAR(GETDATE()), @MES, 1)) Mes#(lf)#(tab),SUM(CASE WHEN DiasCorridos < 3 THEN QuantidadeAtendida ELSE 0 END) RealizadoNumerador #(lf)#(tab),SUM(QuantidadeAtendida) RealizadoDenominador#(lf)FROM tbPdbCalc#(lf)#(lf)DROP TABLE #Filtered_PDB"]),
				    ID_AT = Table.Combine({ID_3140_CustoFrete, ID_0628_ExpD2, ID_0568_IRP, DI_0058_EntregaPrazo, ID_2509_Produtividade, ID_3139_Ageing130, ID_3399_Ageng31, ID_3400_Aging22, ID_2299_Aging15, ID_2985_2986_DiasOs, f_2457DocExp, f_3917VendaDat}),
				    AddColuna = Table.AddColumn(ID_AT, "MesAno", each DateTime.Date(DateTime.From(Text.Combine({Text.From([Mes], "pt-BR"), Text.From([Ano], "pt-BR")}, "/"))), type date),
				    ChvIndicador = Table.AddColumn(AddColuna, "ChvID", each Text.Combine({Text.From([IdIndicador], "pt-BR"), Text.From([Ano], "pt-BR"), Text.From([Mes], "pt-BR")}, "."), type text)
				in
				    ChvIndicador

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

