table f_Sgm
	lineageTag: eaddf7fc-8a96-4858-904a-fecbcfe4e842

	column IdIndicador
		dataType: string
		lineageTag: 1c51e048-631d-44d7-b396-2387ae60cf79
		summarizeBy: none
		sourceColumn: IdIndicador

		annotation SummarizationSetBy = Automatic

	column NomeIndicador
		dataType: string
		lineageTag: 5e1136e5-d597-4b7b-8f4b-42c5ee5b82e3
		summarizeBy: none
		sourceColumn: NomeIndicador

		annotation SummarizationSetBy = Automatic

	column Formula
		dataType: string
		lineageTag: 9f908ae3-3817-464b-902f-503eaa11809f
		summarizeBy: none
		sourceColumn: Formula

		annotation SummarizationSetBy = Automatic

	column Peso
		dataType: int64
		formatString: 0
		lineageTag: b761da55-d5eb-4bc1-9106-4b0559b609bd
		summarizeBy: sum
		sourceColumn: Peso

		annotation SummarizationSetBy = Automatic

	column NomeSetor
		dataType: string
		lineageTag: a9592a14-8186-4bdd-b247-2236e6af83f3
		summarizeBy: none
		sourceColumn: NomeSetor

		annotation SummarizationSetBy = Automatic

	column Mes
		dataType: int64
		formatString: 0
		lineageTag: ce46b86e-dac7-4e85-ada7-b63cd72f17cb
		summarizeBy: sum
		sourceColumn: Mes

		annotation SummarizationSetBy = Automatic

	column Ano
		dataType: int64
		formatString: 0
		lineageTag: db8def9e-9763-43ca-9b85-1d8a83b6f723
		summarizeBy: sum
		sourceColumn: Ano

		annotation SummarizationSetBy = Automatic

	column ChvId
		dataType: string
		lineageTag: c2fdd8ae-7ab1-452d-b578-003e418d9975
		summarizeBy: none
		sourceColumn: ChvId

		annotation SummarizationSetBy = Automatic

	column MesAno
		dataType: dateTime
		formatString: Short Date
		lineageTag: 251ed815-b1b2-4a76-b026-96405728f74d
		summarizeBy: none
		sourceColumn: MesAno

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Realizado =
			
			//VAR real = DIVIDE(f_Sgm[RealNumerador], f_Sgm[RealDenominador], 0)
			VAR real = IF(f_Sgm[RealNumerador] = 0 && f_Sgm[RealDenominador] = 0, 1, DIVIDE(f_Sgm[RealNumerador], f_Sgm[RealDenominador], 0))
			VAR frt = FORMAT(real, "0.####")
			RETURN
			    IF(ISBLANK(f_Sgm[RealNumerador]), BLANK(), frt)
		dataType: double
		lineageTag: 19b32958-0535-42b0-b95b-24bcac32f5c4
		summarizeBy: sum

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column NumAcumulado = ```
			
			VAR acm = 
			    CALCULATE(
			        SUM(f_Sgm[RealNumerador]),
			        FILTER(
			            ALL(f_Sgm),
			            f_Sgm[IdIndicador] = EARLIER(f_Sgm[IdIndicador]) &&
			            f_Sgm[Ano] = EARLIER(f_Sgm[Ano]) &&  -- Filtro para manter o ano
			            f_Sgm[MesAno] <= EARLIER(f_Sgm[MesAno])
			        )
			    )
			RETURN
			    IF(ISBLANK(f_Sgm[RealNumerador]), BLANK(), IF(ISBLANK(acm), 0, acm))
			
			```
		lineageTag: 682977c0-45b8-4fbe-958e-8aedda7f670d
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column DenAcumulado = ```
			
			VAR acm = 
			    CALCULATE(
			        SUM(f_Sgm[RealDenominador]),
			        FILTER(
			            ALL(f_Sgm),
			            f_Sgm[IdIndicador] = EARLIER(f_Sgm[IdIndicador]) &&
			            f_Sgm[Ano] = EARLIER(f_Sgm[Ano]) &&  -- Filtro para manter o ano
			            f_Sgm[MesAno] <= EARLIER(f_Sgm[MesAno])
			        )
			    )
			RETURN
			    IF(ISBLANK(f_Sgm[RealDenominador]), BLANK(), IF(ISBLANK(acm), 0, acm))
			```
		lineageTag: da8f61b7-10a7-43cf-8a91-1fc6057905cd
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column PontuacaoMes =
			SWITCH(TRUE(),
			    f_Sgm[%_AtingReal]>105, 120,
			    f_Sgm[%_AtingReal]>=0.95, 100,
			    f_Sgm[%_AtingReal]>=0.85, 70,
			    f_Sgm[%_AtingReal]>=0, 0
			)
		formatString: 0
		lineageTag: 5930db32-bef9-45b3-bc51-ca4f8ab9b7a1
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column RealAcumulado =
			
			VAR  realacm = DIVIDE(f_Sgm[NumAcumulado],f_Sgm[DenAcumulado],0)
			VAR  frealacm = FORMAT(realacm, "0.##")
			
			RETURN
			    IF(f_Sgm[NumAcumulado] <> BLANK(), frealacm , BLANK())
		dataType: double
		lineageTag: 246e6d84-bb1e-40d8-815d-62af51515eb6
		summarizeBy: sum

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column PontuacaoAcumulado =
			
			VAR pont = SWITCH(TRUE(),
			        f_Sgm[%_AtingAcm]>105, 120,
			        f_Sgm[%_AtingAcm]>=0.95, 100,
			        f_Sgm[%_AtingAcm]>=0.85, 70,
			        f_Sgm[%_AtingAcm]>=0, 0
			    )
			VAR vld = ISBLANK(f_Sgm[RealNumerador]) && ISBLANK(f_Sgm[RealDenominador])
			RETURN
			    IF(vld = FALSE(), pont, BLANK())
		formatString: 0
		lineageTag: 4681d02b-c66c-48ed-b09e-a54abb08ff8f
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column RealNumerador
		dataType: double
		lineageTag: 3930ac0b-8113-4324-bc13-b4d070165297
		summarizeBy: sum
		sourceColumn: RealNumerador

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column RealDenominador
		dataType: double
		lineageTag: 7a26d277-868d-4afd-a344-b54dc8b87ec5
		summarizeBy: sum
		sourceColumn: RealDenominador

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Meta_Indicador
		dataType: double
		formatString: 0.00
		lineageTag: 9c998a0f-65fb-4e78-8e29-cbbe05d4b49a
		summarizeBy: sum
		sourceColumn: Meta_Indicador

		annotation SummarizationSetBy = Automatic

	column %_AtingReal =
			
			VAR div = IF(f_Sgm[Format] = "#,#0.00", 1, 100)
			VAR cima  = DIVIDE(f_Sgm[Realizado], (f_Sgm[Meta_Indicador]/div))
			VAR baixo = (DIVIDE(f_Sgm[Realizado], (f_Sgm[Meta_Indicador]/div))*-1)+2
			VAR fcima = FORMAT(cima, "0.##")
			VAR fbaixo = FORMAT(baixo, "0.##")
			RETURN
			    IF(ISBLANK(f_Sgm[Realizado]), BLANK(),
			        IF(f_Sgm[TpIndicador] = "Para baixo", fbaixo, fcima)
			    )
		dataType: double
		lineageTag: ad81d4d7-4257-4198-9f79-4b86deee4c67
		summarizeBy: sum

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column MetaIndicadorAcumulado
		dataType: double
		lineageTag: 5d09dc0e-55bc-4ec0-8230-ec40b911743c
		summarizeBy: sum
		sourceColumn: MetaIndicadorAcumulado

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column %_AtingAcm =
			
			VAR div = IF(f_Sgm[Format] = "#,#0.00", 1, 100)
			VAR cima  = DIVIDE(f_Sgm[RealizadoAcm], (f_Sgm[MetaIndicadorAcumulado]/div))
			VAR baixo = (DIVIDE(f_Sgm[RealizadoAcm], (f_Sgm[MetaIndicadorAcumulado]/div))*-1)+2
			VAR fcima = FORMAT(cima, "0.####")
			VAR fbaixo = FORMAT(baixo, "0.####")
			RETURN
			    IF(ISBLANK(f_Sgm[Realizado]), BLANK(),
			        IF(f_Sgm[TpIndicador] = "Para baixo", fbaixo, fcima)
			    )
		dataType: double
		lineageTag: 1fa61190-878f-42f4-a4ef-b1d5140d0254
		summarizeBy: sum

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column RealizadoAcm =
			
			VAR real = DIVIDE(f_Sgm[NumAcumulado], f_Sgm[DenAcumulado], 0)
			VAR frt = FORMAT(real, "0.####")
			RETURN
			    IF(ISBLANK(f_Sgm[RealNumerador]), BLANK(), frt)
		dataType: double
		lineageTag: 1c5322f9-65c6-46c7-9723-4e31e253be3c
		summarizeBy: sum

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column TpIndicador
		dataType: string
		lineageTag: 5500e3d2-412b-4057-baff-dcc80abcd7ab
		summarizeBy: none
		sourceColumn: TpIndicador

		annotation SummarizationSetBy = Automatic

	column Format
		dataType: string
		lineageTag: b3f40e36-6e11-404b-8b3c-69dcfa76bfec
		summarizeBy: none
		sourceColumn: Format

		annotation SummarizationSetBy = Automatic

	column FiltroIndicadores = ```
			
			 VAR codId = FORMAT(f_Sgm[IdIndicador]*1, "0000") & " - " 
			 VAR caract = LEN(f_Sgm[NomeIndicador])
			 VAR nomeId = f_Sgm[NomeIndicador]
			 VAR esq = LEFT(nomeId, 15)
			 VAR dir = RIGHT(nomeId, 15)
			 RETURN
			    IF(caract > 30, codId & esq & " ... " & dir,
			        codId & nomeId
			    )
			```
		lineageTag: ed9c8de4-3fa4-4a07-8df3-60295415d068
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Indicadores = ```
			
			 VAR codId = FORMAT(f_Sgm[IdIndicador]*1, "0000") & " - " 
			 VAR nomeId = f_Sgm[NomeIndicador]
			 RETURN
			    codId & nomeId
			```
		lineageTag: 5f55eb27-14c3-4ce2-a94a-602b17f5e5a0
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column FormtMesAno = FORMAT(f_Sgm[MesAno], "mmm"&"/"&"yyyy")
		lineageTag: 0836aad2-0bfa-4d75-8b89-9a3770981020
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition f_Sgm = m
		mode: import
		queryGroup: SGM
		source =
				let
				    Fonte = Sql.Database("PR-S188\DW", "DW", [Query="#(lf)SELECT  *#(lf)#(tab),CAST(IdIndicador AS VARCHAR) + '.' + CAST(Ano AS VARCHAR) + '.' + CAST(Mes AS VARCHAR) ChvId#(lf)#(tab),CAST(CAST(Ano AS VARCHAR) + '-' + CAST(Mes AS VARCHAR) + '-01' AS DATE) MesAno#(lf)FROM AT.GestaoMetas#(lf)WHERE  SetorId = 2#(lf)AND Ano > YEAR(GETDATE())-2"]),
				    TipoAlterado = Table.TransformColumnTypes(Fonte,{{"IdIndicador", type text}}),
				    #"Colunas Renomeadas" = Table.RenameColumns(TipoAlterado,{{"Formato", "Format"}, {"TipoIndicador", "TpIndicador"}}),
				    #"Consultas Mescladas" = Table.NestedJoin(#"Colunas Renomeadas", {"ChvId"}, f_IndicadoresDW, {"ChvID"}, "f_IndicadoresDW", JoinKind.LeftOuter),
				    #"f_IndicadoresDW Expandido" = Table.ExpandTableColumn(#"Consultas Mescladas", "f_IndicadoresDW", {"RealizadoNumerador", "RealizadoDenominador", "DiasUteis"}, {"_RealizadoNumerador", "_RealizadoDenominador", "_DiasUteis"}),
				    #"Soma Inserida" = Table.AddColumn(#"f_IndicadoresDW Expandido", "RealNumerador", each List.Sum({[RealizadoNumerador], [_RealizadoNumerador]}), type number),
				    #"Soma Inserida1" = Table.AddColumn(#"Soma Inserida", "RealDenominador", each List.Sum({[RealizadoDenominador], [_RealizadoDenominador]}), type number),
				    #"Personalização Adicionada" = Table.AddColumn(#"Soma Inserida1", "Meta_Indicador", each if [_DiasUteis] <> null then (([MetaIndicador] / 21)*[_DiasUteis]) else [MetaIndicador], type number),
				    #"Linhas Filtradas" = Table.SelectRows(#"Personalização Adicionada", each ([Formula] <> "Total de peças movimentadas (Exp + Rec) / Qtde de Colaboradores Operacionais")),
				    #"Colunas Removidas" = Table.RemoveColumns(#"Linhas Filtradas",{"SetorId", "MetaIndicador", "RealizadoDenominador", "RealizadoNumerador", "_RealizadoNumerador", "_RealizadoDenominador", "_DiasUteis"}),
				    #"Valor Substituído" = Table.ReplaceValue(#"Colunas Removidas","0,0","0.0",Replacer.ReplaceText,{"Format"}),
				    #"Valor Substituído1" = Table.ReplaceValue(#"Valor Substituído","#.#0.00","#,#0.00",Replacer.ReplaceText,{"Format"})
				in
				    #"Valor Substituído1"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

