table Ocupacao_Diaria
	lineageTag: 9e437b04-1927-4ffa-872c-960c5a9bc984

	column Data
		dataType: dateTime
		formatString: Long Date
		lineageTag: 99daa9d8-b7ae-4362-bdec-a55fdd379ff8
		summarizeBy: none
		sourceColumn: Data

		variation Variation
			isDefault
			relationship: 6a3b7eff-486c-4e8e-9a9a-7afa30e2ec2a
			defaultHierarchy: LocalDateTable_06c1a31b-cc67-4038-a4e6-070a9a3266f8.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Ocupação
		dataType: double
		formatString: #,0.00%;-#,0.00%;#,0.00%
		lineageTag: 0696d99e-6de6-428e-abe0-e80c9cc9b231
		summarizeBy: sum
		sourceColumn: Ocupação

		annotation SummarizationSetBy = Automatic

	column Tipo
		dataType: string
		lineageTag: 217b792b-c8c7-4ede-a44d-1d05230f272b
		summarizeBy: none
		sourceColumn: Tipo

		annotation SummarizationSetBy = Automatic

	partition Ocupacao_Diaria = m
		mode: import
		source =
				let
				    Fonte = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WMjDWNzDTNzIwMlXSUQrILypJVAhIzEktSQVyDXQsjY0MlWJ10JVlJmdn5qWDVZiZmxlDVJgQMMgMizIUg0yBKmIB", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Data = _t, Tipo = _t, Ocupação = _t]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(Fonte,{{"Data", type date}, {"Ocupação", Percentage.Type}})
				in
				    #"Tipo Alterado"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegação

