table Dim_UltimaMov
	lineageTag: 214a5455-e5ee-4a30-ab34-0eb9e2515ce8

	column nro_docto
		dataType: string
		lineageTag: a5bcf6c9-eac9-44bf-b4b3-f5aaaa217077
		summarizeBy: none
		sourceColumn: nro_docto

		annotation SummarizationSetBy = Automatic

	column dt_transf
		dataType: dateTime
		formatString: Long Date
		lineageTag: b3cac3a9-73a2-4eba-a227-59eb2d3b9de3
		summarizeBy: none
		sourceColumn: dt_transf

		variation Variation
			isDefault
			relationship: b3b7c57f-e0e7-4ae1-8db3-2a047f17a33a
			defaultHierarchy: LocalDateTable_64ceffc8-9661-4f23-8206-c9e094ac21cb.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column usuario
		dataType: string
		lineageTag: d9e2aa0c-f3cf-4750-9310-b2c951eed0b2
		summarizeBy: none
		sourceColumn: usuario

		annotation SummarizationSetBy = Automatic

	column it_codigo
		dataType: string
		lineageTag: 64b46412-3426-4d66-bcea-09b2027466f8
		summarizeBy: none
		sourceColumn: it_codigo

		annotation SummarizationSetBy = Automatic

	column Saldo_AAT = COALESCE(RELATED(Dim_AAT[Quantidade]),0)
		formatString: 0
		lineageTag: 07f76fc6-9f5a-4ea6-a95b-bd6277f02233
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column Saldo_DCV =
			
			COALESCE(LOOKUPVALUE(
			    Dim_DCV[Quantidade],
			    Dim_DCV[Item], Dim_UltimaMov[it_codigo]
			),0)
		formatString: 0
		lineageTag: f6cb9a86-7860-4896-a559-ca69ab692293
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	partition Dim_UltimaMov = m
		mode: import
		source =
				let
				    Fonte = Sql.Database("PR-S188\DW", "DW", [Query="WITH UltimaSaida AS (#(lf)    SELECT #(lf)        CASE #(lf)            WHEN LEN(Mov.[it-codigo]) < 6 #(lf)                THEN RIGHT(REPLICATE('0', 6) + Mov.[it-codigo], 6) #(lf)            ELSE Mov.[it-codigo] #(lf)        END AS it_codigo,#(lf)        Mov.[nro-docto] AS nro_docto,#(lf)        CONVERT(VARCHAR(10), Mov.[dt-trans], 103) AS dt_transf,#(lf)        Mov.[usuario] AS usuario,#(lf)        ROW_NUMBER() OVER (#(lf)            PARTITION BY #(lf)                CASE #(lf)                    WHEN LEN(Mov.[it-codigo]) < 6 #(lf)                        THEN RIGHT(REPLICATE('0', 6) + Mov.[it-codigo], 6) #(lf)                    ELSE Mov.[it-codigo] #(lf)                END#(lf)            ORDER BY Mov.[dt-trans] DESC, Mov.[hr-trans] DESC#(lf)        ) AS rn#(lf)    FROM [STAGE].[tot].[MovtoEstoq] AS Mov#(lf)    #(lf)    WHERE Mov.[cod-estabel] = '15'#(lf)      AND Mov.[dt-trans] BETWEEN '2020-01-01' AND GETDATE()#(lf)      AND Mov.[cod-depos] IN ('AAT','ATE','DCV','DES','DAT','AIR','REC','RCB','DEV','NAT','LGR')#(lf)      AND Mov.[esp-docto] IN (5,6,15,20,21,22,23,28,31,33)#(lf)      AND Mov.[quantidade] <> 0#(lf)      AND Mov.[tipo-trans] = 2#(lf))#(lf)SELECT nro_docto, dt_transf, usuario, it_codigo#(lf)FROM UltimaSaida#(lf)#(lf)#(lf)WHERE rn = 1"]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(Fonte,{{"dt_transf", type date}})
				in
				    #"Tipo Alterado"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

