table Fato_Mov_Inv
	lineageTag: 8da76018-e156-47cd-99fe-1c47947b7b0f

	column Documento
		dataType: double
		lineageTag: b497d00d-4061-402a-afbe-3c500b1c0cba
		summarizeBy: sum
		sourceColumn: Documento

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column DataImplant
		dataType: dateTime
		formatString: Short Date
		lineageTag: 7c5f74ac-2962-4f9d-9bb1-afd1460edd1e
		summarizeBy: none
		sourceColumn: DataImplant

		variation Variation
			isDefault
			relationship: c0eacb1d-585c-4411-a6f6-02a565fc466a
			defaultHierarchy: LocalDateTable_39216eae-85db-406e-a9a5-3e4be7958b3c.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column NumeroDocumento
		dataType: string
		lineageTag: 947365ef-0b23-4961-b419-46e41ce40e8c
		summarizeBy: none
		sourceColumn: NumeroDocumento

		annotation SummarizationSetBy = Automatic

	column HoraCriacaoDoc
		dataType: string
		lineageTag: e986a4a5-0c04-4ada-a1e7-53a8b5c08f8f
		summarizeBy: none
		sourceColumn: HoraCriacaoDoc

		annotation SummarizationSetBy = Automatic

	column Situacao
		dataType: string
		lineageTag: ba060d95-8879-4003-94dd-ff91de743d51
		summarizeBy: none
		sourceColumn: Situacao

		annotation SummarizationSetBy = Automatic

	column IdEndereco
		dataType: double
		lineageTag: d001fcbd-67b4-483c-9e90-3736d79c65de
		summarizeBy: sum
		sourceColumn: IdEndereco

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Endereco
		dataType: string
		lineageTag: 9b9691cc-ae9f-4319-afff-8cb6579445cc
		summarizeBy: none
		sourceColumn: Endereco

		annotation SummarizationSetBy = Automatic

	column Item
		dataType: string
		lineageTag: 7aba28e8-dc43-4878-ba14-64b6a04a824d
		summarizeBy: none
		sourceColumn: Item

		annotation SummarizationSetBy = Automatic

	column DescItem
		dataType: string
		lineageTag: a6ff1dd7-68ec-4133-91ef-394dad67daca
		summarizeBy: none
		sourceColumn: DescItem

		annotation SummarizationSetBy = Automatic

	column QtdeItemMov
		dataType: int64
		formatString: 0
		lineageTag: 07a59d3e-b869-410e-a53c-6ca4f0eb9265
		summarizeBy: sum
		sourceColumn: QtdeItemMov

		annotation SummarizationSetBy = Automatic

	column DataCarga
		dataType: dateTime
		formatString: General Date
		lineageTag: 042961cc-95bd-4331-a95d-c4dee44f4b39
		summarizeBy: none
		sourceColumn: DataCarga

		variation Variation
			isDefault
			relationship: 1c760636-72f8-494e-ad2e-74f1b32e41ec
			defaultHierarchy: LocalDateTable_15ec86a7-edfc-4736-843b-e2c757f0e359.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	partition Fato_Mov_Inv = m
		mode: import
		source =
				let
				    Fonte = Sql.Database("PR-S188\DW", "DW", [Query="WITH CTE AS (#(lf)    SELECT *,#(lf)           ROW_NUMBER() OVER (#(lf)               PARTITION BY Documento, SequenciaMovto, HoraInicio#(lf)               ORDER BY DataImplantacao DESC#(lf)           ) AS rn#(lf)    FROM DW.logistica.Fato_Mov_Estoque_PA_AT AS DOC#(lf)    WHERE [Local] = 'AAT'#(lf)      AND (NumeroDocumento LIKE 'RUA/%' OR NumeroDocumento LIKE 'PCK/%' OR NumeroDocumento LIKE 'VAL/%')#(lf)      AND DOC.DataImplantacao >= '2026-01-21'#(lf)      AND Situacao = 'Atualizado'#(lf))#(lf)SELECT #(lf)Documento,#(lf)CONVERT(VARCHAR(10), CTE.DataImplantacao, 103) AS DataImplant,#(lf)NumeroDocumento,#(lf)HoraCriacaoDoc,#(lf)Situacao,#(lf)IdEndereco,#(lf)Endereco,#(lf)Item,#(lf)IT.DescItem,#(lf)QtdeItemMov,#(lf)DataCarga#(lf)FROM CTE#(lf)LEFT JOIN DW.dbo.Dim_Item AS IT#(lf)ON IT.CodItem = Item#(lf)WHERE rn = 1"]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(Fonte,{{"DataImplant", type date}})
				in
				    #"Tipo Alterado"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

