table Dim_Data
	lineageTag: bbc800e2-dadc-4826-8961-1a75541a8cbf

	column Data
		dataType: dateTime
		formatString: General Date
		lineageTag: 9b15d966-ae5d-4fea-862b-4a57961982ed
		summarizeBy: none
		sourceColumn: Data

		variation Variation
			isDefault
			relationship: 91044c1e-b2f7-4486-a049-1b2a74485c1c
			defaultHierarchy: LocalDateTable_d840ba8d-8965-4643-b20e-d141b612b84d.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column DataMascara
		dataType: string
		lineageTag: cd1ac765-e3b7-423d-8d46-f65fc6fa1526
		summarizeBy: none
		sourceColumn: DataMascara

		annotation SummarizationSetBy = Automatic

	column MesNome
		dataType: string
		lineageTag: f6795a37-2c71-4305-8450-feb811a3964b
		summarizeBy: none
		sourceColumn: MesNome

		annotation SummarizationSetBy = Automatic

	column Ano
		dataType: string
		lineageTag: e90b95f3-4ef7-4c36-a729-46468f8bf602
		summarizeBy: none
		sourceColumn: Ano

		annotation SummarizationSetBy = Automatic

	column DiaSemanaNomAbrev
		dataType: string
		lineageTag: 8e91541f-4559-49ff-b98a-1af7238a9b60
		summarizeBy: none
		sourceColumn: DiaSemanaNomAbrev

		annotation SummarizationSetBy = Automatic

	column SemestreNome
		dataType: string
		lineageTag: b10bd098-95c0-4f36-b329-baf0332b8cbb
		summarizeBy: none
		sourceColumn: SemestreNome

		annotation SummarizationSetBy = Automatic

	column DiaUtil
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: af588546-1e31-46ba-816c-8cf06a79703d
		summarizeBy: none
		sourceColumn: DiaUtil

		annotation SummarizationSetBy = Automatic

	column Mes
		dataType: string
		lineageTag: f127db10-0a65-489e-a253-53631da01109
		summarizeBy: none
		sourceColumn: Mes

		annotation SummarizationSetBy = Automatic

	column Feriado
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 92814a7f-6f72-457a-af45-d9e24cbc44f0
		summarizeBy: none
		sourceColumn: Feriado

		annotation SummarizationSetBy = Automatic

	partition Dim_Data = m
		mode: import
		queryGroup: 'Tabelas DIM'
		source =
				let
				   Fonte = Sql.Database("PR-S188\DW", "DW", [Query="#(lf)        DECLARE @RangeStart DATETIME = '2025-01-01';#(lf)        DECLARE @RangeEnd DATETIME = GETDATE();#(lf)#(lf)        SELECT #(lf)            Data,#(lf)            Mes,#(lf)            MesNome,#(lf)            SemestreNome,#(lf)            Ano,#(lf)            Feriado,#(lf)            DiaUtil,#(lf)            DiaSemanaNomAbrev,#(lf)            DataMascara#(lf)        FROM dbo.Dim_Data#(lf)        WHERE Data > @RangeStart AND Data <= @RangeEnd#(lf)    "]),
				    #"Linhas Filtradas" = Table.SelectRows(Fonte, each [Data] > RangeStart and [Data] <= RangeEnd)
				in
				    #"Linhas Filtradas"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Exception

