table Dim_Data_Fin
	lineageTag: 3d97d2c5-b767-480a-a4c6-63ca92d98461

	column DiaUtil
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: c9b1760a-38ca-4e5b-afeb-6c6ae8594498
		summarizeBy: none
		sourceColumn: DiaUtil

		annotation SummarizationSetBy = Automatic

	column Mes
		dataType: string
		lineageTag: 38e0bb93-aedf-44bc-9754-fc6617dd88f8
		summarizeBy: none
		sourceColumn: Mes

		annotation SummarizationSetBy = Automatic

	column Data
		dataType: dateTime
		formatString: General Date
		lineageTag: d7af9a59-3f43-45cb-8aad-0868781d0ffe
		summarizeBy: none
		sourceColumn: Data

		variation Variation
			isDefault
			relationship: c7149172-076b-41e9-bdd2-ed593b14ecfb
			defaultHierarchy: LocalDateTable_7d1b562d-293b-4e18-8c69-645db63d435b.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column MesAbrev
		dataType: string
		lineageTag: 9fed3ad9-9574-4eff-9c68-4dd74e003a13
		summarizeBy: none
		sourceColumn: MesAbrev
		sortByColumn: Mes

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	partition Dim_Data_Fin = m
		mode: import
		source =
				let
				    Fonte = Sql.Database("PR-S188\DW", "DW", [Query="SELECT #(lf)    [Id],#(lf)    [Data],#(lf)    [MesNome],#(lf)    [Mes],#(lf)    LEFT([MesNome], 3) AS MesAbrev,#(lf)    [Feriado],#(lf)    [DiaUtil],#(lf)    [DiaSemanaNomAbrev]#(lf)FROM [DW].[dbo].[Dim_Data]#(lf)WHERE [Data] >= '2024-01-01'#(lf)  AND [Data] <= CAST(GETDATE() AS DATE)"]),
				    #"Linhas Filtradas" = Table.SelectRows(Fonte, each [Data] > RangeStart and [Data] <= RangeEnd),
				    #"Columns removed by Measure Killer"= Table.SelectColumns(#"Linhas Filtradas",{"DiaUtil","Mes","Data","MesAbrev"})
				in
				    #"Columns removed by Measure Killer"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

